version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # Maintain go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
