name: Update Changelog

on:
  pull_request:
    types: [ closed ]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged == true
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Update Changelog
      uses: ./
